### ISSUE TITLE
Bug: AceHook Issue

### ISSUE THREAD

**Issue by nancikennedy** [Numynum/TalentTreeTweaks#10]
On Retail, using 1.5.4 of TTT, an error is generated when switching specs:

2x Ace3/AceHook-3.0-9/AceHook-3.0.lua:180: Attempting to rehook already active hook tooltipTranslation.
[string "=[C]"]: ?
[string "@Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:180: in function <Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:321: in function `RawHook'
[string "@TalentTreeTweaks/modules/exportInspectedBuild.lua"]:70: in function <...ns/TalentTreeTweaks/modules/exportInspectedBuild.lua:69>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetSelectionOptions'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:647: in function `RefreshLoadoutOptions'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:271: in function <...ard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua:232>

Locals:
(*temporary) = "Attempting to rehook already active hook tooltipTranslation."

**Comment by Numynum** [comment]
thanks, should now be fixed :)
