### ISSUE TITLE
[Error] Consistent LUA error when opening talent frame

### ISSUE THREAD

**Issue by fearkite** [Numynum/TalentTreeTweaks#11]
I get this LUA error issue every time I open the talent frame

Message: ...ns/TalentTreeTweaks/modules/exportInspectedBuild.lua:84: attempt to index field 'exportButton' (a nil value)
Time: Wed Jan 25 11:46:55 2023
Count: 5
Stack: ...ns/TalentTreeTweaks/modules/exportInspectedBuild.lua:84: attempt to index field 'exportButton' (a nil value)
[string "@Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua"]:84: in function `UpdateExportButton'
[string "@Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua"]:40: in function <...ns/TalentTreeTweaks/modules/exportInspectedBuild.lua:40>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UpdateInspecting'
[string "@Interface/AddOns/Blizzard_ClassTalentUI/Blizzard_ClassTalentFrameTemplate.lua"]:132: in function `SetInspecting'
[string "@Interface/FrameXML/UIParent.lua"]:957: in function `ToggleTalentFrame'
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 UpdateExportButton = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:81
 Enable = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:394
 GetName = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:34
 name = "TalentTreeTweaks_ExportInspectedBuild"
 IsEnabled = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 HookScript = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:365
 IsHooked = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:492
 baseName = "TalentTreeTweaks"
 IsModule = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 SetupHook = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:38
 GetDescription = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:27
 SetEnabledState = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 OnDisable = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:17
 OnEnable = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:11
 shouldShowExportButton = false
 OnSetSelectionOptions = <function> defined @Interface/AddOns/TalentTreeTweaks/modules/exportInspectedBuild.lua:69
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SecureHook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:335
 IterateModules = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UnhookAll = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.l

**Comment by Numynum** [comment]
should be fixed now (by #12)
update will be downloadable soon ™️
