### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by agentschmitt** [Numynum/TalentTreeTweaks#13]
Hi i have alwaxs a lua error by TalentTreeTweaks in the beginning of Ruby Life Pools Mythic+.
Also the game starts to lag their until i rellog my character then.

1x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' hat versucht die geschützte Funktion 'StanceBar:SetPointBase()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function <FrameXML/EditModeManager.lua:617>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/ActionBar.lua"]:371: in function `UpdateVisibility'
[string "@FrameXML/ActionBar.lua"]:338: in function `HideOverride'
[string "@FrameXML/ActionBar.lua"]:323: in function `SetShown'
[string "@FrameXML/StanceBar.lua"]:31: in function `Update'
[string "@FrameXML/ActionBarController.lua"]:81: in function <FrameXML/ActionBarController.lua:55>

**Comment by Numynum** [comment]
does this also happen when TalentTreeTweaks disabled?
I've never seen this myself personally

**Comment by agentschmitt** [comment]
I was running ruby life pools today again and the error did not occur anymore. Two days ago i had it 3 times ^^
Maybe it was related to another addon and fixed by update now.
So i think we can close it.

**Comment by agentschmitt** [comment]
today i had the same error again on the last mobs in Nokhud Offensive.
i think i opened my character interface during combat, then the lua error popped up and game started to lag.
but still not sure if its talentreetweaks. when i kno how to reproduce it i will test without TalentTreeTweaks ;)
