### ISSUE TITLE
Feature Suggestion - Automatically Change Gearsets

### ISSUE THREAD

**Issue by Jaxar** [Numynum/TalentTreeTweaks#14]
It would be nice if when we change talents it could change to saved gearsets. Gearsets change automatically when you change spec in base UI but I cant see a way to automatically do it when changing talent loadouts.

I assume this may be something that you need to add along with adding additional loadout options but I created a new suggestion incase its simpler then I think.

**Comment by Numynum** [comment]
hi, I want to focus on talents, and making it easier to manage them

while I understand the appeal of this feature (and agree that it's a useful feature for sure), I'll leave it for other addon developers to create, since they'll do a much better job I imagine 🙂
