### ISSUE TITLE
Addon causing microstutters

### ISSUE THREAD

**Issue by birdfighter** [Numynum/TalentTreeTweaks#15]
I noticed a fair amount of microstutters while trying out this addon.

These are my frametimes captured while not doing anything ingame, no movement/mouse movement in a dead location (legion dalaran)

With the addon disabled:
![image](https://user-images.githubusercontent.com/83915265/220466690-e5659bff-f16d-45f3-9cfa-9cdeda769659.png)
With the addon enabled:
![image](https://user-images.githubusercontent.com/83915265/220466770-5e7e8ec0-6949-40a7-ab2f-2d5cb908ed01.png)

For comparison, this is with and without ElvUI enabled:
![image](https://user-images.githubusercontent.com/83915265/220467922-f554ee05-5118-48c6-8372-781af257100f.png)
![image](https://user-images.githubusercontent.com/83915265/220467929-9e2f5940-d4f8-4ac8-8515-384b811460a2.png)

Running the version 1.6.2

**Comment by birdfighter** [comment]
Seems like it comes from this module, makes sense since I have tradechat etc enabled

With module disabled:
![image](https://user-images.githubusercontent.com/83915265/220471310-38319188-a768-4bca-94d1-9b2eb19f992e.png)

**Comment by Numynum** [comment]
I've pushed a release that should improve things
I play on a quiet realm, so it's hard to see any difference; could you see if it helps?

**Comment by birdfighter** [comment]
Great improvement, FPS increased by around 7% for me when idling in cities and the stutter is as good as gone, or at least related to this addon.
Pre update 
![image](https://user-images.githubusercontent.com/83915265/220666774-cc682b89-5868-4ace-9fe1-d4b9a8ebba59.png)
Post update
![image](https://user-images.githubusercontent.com/83915265/220666831-ae9cded9-eb6d-4fb1-a499-467eac403195.png)
Pre updated with chat disabled (reference)
![image](https://user-images.githubusercontent.com/83915265/220666981-0e2879aa-9e7f-49bd-8d00-3b4f2ed225e3.png)
