### ISSUE TITLE
Error usually after inpecting other players

### ISSUE THREAD

**Issue by stamicvs** [Numynum/TalentTreeTweaks#16]
If I inspect other players and open their talent tree I get a lot of errors. This happens during combat heavily especially on moseover but also out of combat.
One one quick LFR runs I inpected a player out of combat an after a while I received this error:

`7x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'MultiBarBottomLeft:SetFrameStrata()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetFrameStrata'
[string "@FrameXML/ActionBar.lua"]:207: in function `UpdateFrameStrata'
[string "@FrameXML/ActionBar.lua"]:195: in function `SetShowGrid'
[string "@FrameXML/MultiActionBars.lua"]:85: in function `MultiActionBar_ShowAllGrids'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentFrameTemplate.lua"]:36: in function <..._ClassTalentUI/Blizzard_ClassTalentFrameTemplate.lua:24>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@TalentTreeTweaks/modules/reduceTaint.lua"]:61: in function <...faceTalentTreeTweaks/modules/reduceTaint.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:959: in function `ToggleTalentFrame'
[string "@Blizzard_InspectUI/InspectPaperDollFrame.lua"]:204: in function <Blizzard_InspectUI/InspectPaperDollFrame.lua:198>`

**Comment by Numynum** [comment]
that specific error should be resolved next update
