### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by omgsquashattack** [Numynum/TalentTreeTweaks#17]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'TalentTreeTweaks' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR3BUTTON2"]:2: in function <[string "MULTIACTIONBAR3BUTTON2"]:1>

**Comment by Numynum** [comment]
can you get this error consistently?
does it occur with no other addons enabled?
what are you doing to trigger the error?
