### ISSUE TITLE
Feature Request: Passive vs Active highlighting

### ISSUE THREAD

**Issue by nancikennedy** [Numynum/TalentTreeTweaks#6]
A visual indicator distinguishing between active and passive talents would be most welcome.

This addon is such a major quality of life improvement! Good job. :)

**Comment by Numynum** [comment]
glad you like it :)

blizzard already shows a very clear difference between actives and passives actually 🙂, passives are round, actives are square
example screenshot:
![image](https://user-images.githubusercontent.com/17293527/208257004-860c01b3-6d4e-4d7d-b928-942dd5fdaa14.png)

**Comment by nancikennedy** [comment]
/facepalm
I....just....wow. Thanks for pointing that out to me, 'cause that completely blew past me. /laugh
