### ISSUE TITLE
Desaturation of Active Specialization

### ISSUE THREAD

**Issue by kageus** [Numynum/TalentTreeTweaks#8]
From user perspective it feels off that active spec is grayed out on the talent repec buttons.  I inverted the saturation change in the respecButton module and it seemed more intuitive.  Keeps the same functionality, just changes the appearance so the innactive spec is the one grayed out.

**Comment by kageus** [comment]
Played with a PR to turn this into an option, but my lua skills were lacking and I kept getting null db

**Comment by Numynum** [comment]
I'll have a bit of a okay myself 
the initial reasoning, was that I disabled the button for the current spec, and disabled buttons should be desaturated :)
though it'd also make intuitive sense to highlight the active spec instead

**Comment by kageus** [comment]
I think the initial reasoning is sound.   For me it comes down to which inactive thing is de-emphasized, inactive spec or inactive button.  And that's likely a personal preference.  

I did find that on classes with only 2 specializations and therefore only 2 buttons, I kept looking down and wondering why my inactive specialization is the one that's lit up, or thinking that I'd somehow switched specs.   Less of an issue with 3+ spec classes where there are 2+ lit up inactive specs.

**Comment by kageus** [comment]
FYI:  After swapping saturation rules on my local copy for a week I've decided to switch back to default.  Going to close my issue
