### ISSUE TITLE
Feature Suggestion - Multi-Rank Cascade Repurchasable Indicator

### ISSUE THREAD

**Issue by jsutan** [Numynum/TalentTreeTweaks#9]
If it is possible, can you add a points spent indicator to the multi-rank talents when you remove lower tier talents that break the higher tier unlock requirements? 

Original:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/6308057/211166117-484b6980-b2f5-465e-bec3-47006ac72e57.png">

After removing a lower tier talent using the addon for Cascade Repurchasable Indicator:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/6308057/211166129-e467df54-4d80-442f-8b78-b54b59dadb22.png">

Example mockup of what feature this is requesting:

![image](https://user-images.githubusercontent.com/6308057/211166234-2c6438f2-65eb-4aac-b480-b9d59e1f5958.png)

**Comment by Numynum** [comment]
Hi, sorry for the (rather lengthy) delay
I've looked into this a bit, but unfortunately I don't see any way to find out how many ranks were purchased, before they got removed
it would be nice to have this info, but I don't think it'll happen sadly :/
